name: Update Weather for Korean Cities

on:
  schedule:
    - cron: "*/15 * * * *"  # 15분마다
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Ensure cities directory exists
        run: mkdir -p cities

      - name: Update weather files
        env:
          APIKEY: ${{ secrets.OPENWEATHER_APIKEY }}
        run: |
          echo "준비중..." > cities/.placeholder

          if [ ! -f cities.txt ]; then
            echo "cities.txt 파일이 없습니다."
            exit 1
          fi

          while IFS= read -r LINE || [ -n "$LINE" ]; do
            # 빈 줄은 건너뜀
            if [ -z "$LINE" ]; then continue; fi

            # 한글:영문 분리
            CITY_HANGUL=$(echo "$LINE" | cut -d':' -f1)
            CITY_EN=$(echo "$LINE" | cut -d':' -f2)

            if [ -z "$CITY_HANGUL" ] || [ -z "$CITY_EN" ]; then continue; fi

            # URL 인코딩
            ENCODED=$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))" "$CITY_EN")

            # API 호출
            DATA=$(curl -s "https://api.openweathermap.org/data/2.5/weather?q=$ENCODED&units=metric&lang=kr&appid=$APIKEY")

            # 오류 처리
            CODE=$(echo "$DATA" | jq -r '.cod // empty')
            if [ "$CODE" = "401" ] || [ "$CODE" = "404" ]; then
              echo "$CITY_HANGUL: 준비중..." > "cities/$CITY_HANGUL.txt"
              continue
            fi

            TEMP=$(echo "$DATA" | jq '.main.temp' | xargs printf "%.0f")
            DESC=$(echo "$DATA" | jq -r '.weather[0].description')
            HUM=$(echo "$DATA" | jq '.main.humidity')
            WIND=$(echo "$DATA" | jq '.wind.speed')

            echo "${CITY_HANGUL} 날씨: ${DESC}, ${TEMP}°C, 습도 ${HUM}%, 풍속 ${WIND}m/s" > "cities/$CITY_HANGUL.txt"
          done < cities.txt

      - name: Commit changed files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cities/*.txt || true
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "Update city weather" || exit 0
          git push
