name: Update Weather

on:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다 실행
  workflow_dispatch:          # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Seoul weather and update file
        run: |
          CITY="Seoul"
          APIKEY="5954fc895aad795b708f0e2665c7403e"
          DATA=$(curl -s "https://api.openweathermap.org/data/2.5/weather?q=$CITY&units=metric&lang=kr&appid=$APIKEY")
          TEMP=$(echo $DATA | jq '.main.temp' | xargs printf "%.0f")
          DESC=$(echo $DATA | jq -r '.weather[0].description')
          HUM=$(echo $DATA | jq '.main.humidity')
          echo "서울 날씨: ${DESC}, ${TEMP}°C, 습도 ${HUM}%" > weather.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.txt
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "Update weather"
          git push
